<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
	<link rel="stylesheet" href="/static/css/main.css">
	<link href="//vjs.zencdn.net/5.19/video-js.min.css" rel="stylesheet">

	<link rel="apple-touch-icon" sizes="180x180" href="/static/favicon/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="/static/favicon/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="/static/favicon/favicon-16x16.png">
	<link rel="manifest" href="/static/favicon/site.webmanifest">
	<link rel="mask-icon" href="/static/favicon/safari-pinned-tab.svg" color="#ff0000">
	<link rel="shortcut icon" href="/static/favicon/favicon.ico">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-config" content="/static/favicon/browserconfig.xml">
	<meta name="theme-color" content="#ffffff">

	<title>VIDEO MANAGER</title>
</head>
<body class="page">

<div class="layout-wrapper">
	<!--
	<header class="layout-header" itemscope="itemscope" itemtype="http://schema.org/WPHeader">
	    <div class="layout-header__wrapper">

	        <a href="./index.html" class="layout-header__logo logo" rel="home" itemprop="url" accesskey="1" data-instant>
	            <span itemprop="name"></span>
	        </a>

	    </div>
	</header>
	-->

    <div class="layout-wrapper__container">

        <aside class="sidebar" itemscope="itemscope" itemtype="http://schema.org/WPSideBar">
        	<?php foreach ($this->data as $name => $file): ?>
    		<!-- is-active -->
			<button type="button" class="video-item j-load-video" data-video="<?= $file->video ?>" data-poster="<?= $file->poster ?>">
				<img src="<?= $file->preview ?>" class="video-item__image" alt="">
				<span class="video-item__name"><?= $name ?></span>
			</button>
        	<?php endforeach; ?>

			<!--
			<button type="button" class="video-item is-active j-load-video" data-video="/files/out.mp4" data-poster="/files/poster.jpg">
				<img src="/files/poster.jpg" class="video-item__image" alt="">
			</button>

			<button type="button" class="video-item j-load-video" data-video="/files/out.mp4" data-poster="/files/poster.jpg">
				<img src="/files/poster.jpg" class="video-item__image" alt="">
			</button>

			<button type="button" class="video-item j-load-video" data-video="/files/out.mp4" data-poster="/files/poster.jpg">
				<img src="/files/poster.jpg" class="video-item__image" alt="">
			</button>

			<button type="button" class="video-item j-load-video" data-video="/files/out.mp4" data-poster="/files/poster.jpg">
				<img src="/files/poster.jpg" class="video-item__image" alt="">
			</button>

			<button type="button" class="video-item j-load-video" data-video="/files/out.mp4" data-poster="/files/poster.jpg">
				<img src="/files/poster.jpg" class="video-item__image" alt="">
			</button>

			<button type="button" class="video-item j-load-video" data-video="/files/out.mp4" data-poster="/files/poster.jpg">
				<img src="/files/poster.jpg" class="video-item__image" alt="">
			</button>

			<button type="button" class="video-item j-load-video" data-video="/files/out.mp4" data-poster="/files/poster.jpg">
				<img src="/files/poster.jpg" class="video-item__image" alt="">
			</button>

			<button type="button" class="video-item j-load-video" data-video="/files/out.mp4" data-poster="/files/poster.jpg">
				<img src="/files/poster.jpg" class="video-item__image" alt="">
			</button>

			<button type="button" class="video-item j-load-video" data-video="/files/out.mp4" data-poster="/files/poster.jpg">
				<img src="/files/poster.jpg" class="video-item__image" alt="">
			</button>
			-->
		</aside>

        <main class="content">
 			<!-- controls -->
 			<!-- poster="//vjs.zencdn.net/v/oceans.png"  -->

			<video id="player" class="video-js" preload="auto" data-setup='{}'>
		  		<!-- <source src="/files/out.mp4" type="video/mp4"></source> -->
		  		<!-- <source src="/files/video_1080p_2018_03_29_16_10_14.mp4" type="video/mp4"></source> -->
			</video>

			<button class="button" id="send-video">Отправить видео</button>

        </main>

    </div>

</div>

<script src="//vjs.zencdn.net/5.19/video.min.js"></script>
<script src="/static/js/app.js"></script>

</body>
</html>