<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">

	<link rel="stylesheet" href="/static/css/base.css">
	<link rel="stylesheet" href="/static/css/main.css">
	<link rel="stylesheet" href="/static/css/video-js.min.css">

	<link rel="apple-touch-icon" sizes="180x180" href="/static/favicon/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="/static/favicon/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="/static/favicon/favicon-16x16.png">
	<link rel="manifest" href="/static/favicon/site.webmanifest">
	<link rel="mask-icon" href="/static/favicon/safari-pinned-tab.svg" color="#ff0000">
	<link rel="shortcut icon" href="/static/favicon/favicon.ico">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-config" content="/static/favicon/browserconfig.xml">
	<meta name="theme-color" content="#ffffff">

	<title>VIDEO MANAGER</title>
</head>
<body class="page">

<div class="layout-wrapper">

	<template id="tmpl-send-message">
		<div class="modal" aria-hidden="true" tabindex="-1" id="send-message">
			<form action="/api/send-message" method="POST" class="modal__dialog j-ajax-form">
				<button type="button" class="modal__close j-close-modal" data-target="#send-message"></button>

				<div class="modal__header">
					<div class="modal__title">Отправить видео</div>
				</div>

				<div class="modal__body">
					<label class="label">
						<span class="label__name">Имя</span>
						<input name="name" class="input">
					</label>

					<label class="label">
						<span class="label__name">Номер телефона</span>
						<input name="phone" class="input">
					</label>

					<label class="label">
						<span class="label__name">Электронная почта</span>
						<input name="email" class="input">
					</label>
				</div>

				<div class="modal__footer">
					<button type="reset" class="button-reset j-close-modal">Отменить</button>
					<button type="submit" class="button-submit">Отправить</button>
				</div>
			</form>
		</div>
	</template>

    <div class="layout-wrapper__container">

        <aside class="sidebar" id="sidebar">
        	<?php foreach ($this->data as $name => $file): ?>
    		<button type="button" class="video-item j-load-video" data-video="<?= $file->video ?>" data-poster="<?= $file->poster ?>">
				<img src="<?= $file->preview ?>" class="video-item__image" alt="">
				<span class="video-item__name"><?= $name ?></span>
			</button>
        	<?php endforeach; ?>
		</aside>

        <div class="container">
        	<header class="header">

        		<div class="header__event">
        			Наименование Мероприятия
        		</div>

		        <div class="logo"></div>
			</header>

			<main class="content" id="content">

				<video id="player" class="video-js vjs-default-skin vjs-16-9" controls preload="auto" data-setup='{"width":auto,"height":auto,"fluid":true,"aspectRatio":"4:3"}'>
			  		<!-- <source src="/files/out.mp4" type="video/mp4"></source> -->
			  		<!-- <source src="/files/video_1080p_2018_03_29_16_10_14.mp4" type="video/mp4"></source> -->
				</video>

				<button class="button j-open-modal" data-modal="tmpl-send-message" id="send-video">Отправить на почту</button>

	        </main>
        </div>

    </div>

</div>

<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/video.min.js"></script>
<script src="/static/js/template7.min.js"></script>
<script src="/static/js/modal.min.js"></script>
<script src="/static/js/app.js"></script>

</body>
</html>