<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">

	<link rel="stylesheet" href="/static/css/base.css">
	<link rel="stylesheet" href="/static/css/main.css">
	<link rel="stylesheet" href="/static/css/video-js.min.css">

	<link rel="apple-touch-icon" sizes="180x180" href="/static/favicon/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="/static/favicon/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="/static/favicon/favicon-16x16.png">
	<link rel="manifest" href="/static/favicon/site.webmanifest">
	<link rel="mask-icon" href="/static/favicon/safari-pinned-tab.svg" color="#ff0000">
	<link rel="shortcut icon" href="/static/favicon/favicon.ico">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-config" content="/static/favicon/browserconfig.xml">
	<meta name="theme-color" content="#ffffff">

	<?php $mode = (!empty($this->params['mode'])) ? $this->params['mode'] : 'video'; ?>

	<script>
		var mode = '<?= $mode; ?>'
		var baseTimeout = '<?= $this->params['time']; ?>'
	</script>

	<title>VIDEO MANAGER</title>
</head>
<body class="page" style="background-color: <?= $this->params['style_body_bg']; ?>; color: <?= $this->params['style_body_text']; ?>;">

<div class="layout-wrapper">

	<template id="tmpl-gif">
		<img src="{{ src }}" alt="" class="video-gif__image">
	</template>

	<template id="tmpl-preloader">
		<div class="preloader">
			<span class="preloader__bullet"></span>
			<span class="preloader__bullet"></span>
			<span class="preloader__bullet"></span>
		</div>
	</template>

	<template id="tmpl-video-item">
		<button type="button" class="video-item j-play-video" data-mode="{{ mode }}" id="{{ id }}" data-video="{{ file.video }}" data-poster="{{ file.poster }}">
			<img src="{{ file.preview }}" class="video-item__image" alt="">
			<span class="video-item__name">{{ file.name }}</span>
		</button>
	</template>

	<template id="tmpl-popup-message">
	    <div class="popup-mesage" id="popup-message" aria-hidden="true" tabindex="-1">
	        <button class="popup-mesage__close j-close-modal" data-target="#popup-message" aria-label="Закрыть"></button>

	        {{#if title}}
	        <header class="popup-mesage__header popup-mesage__header--success">
	            {{title}}
	        </header>
	        {{/if}}

	        {{#if message}}
	        <div class="popup-mesage__body">
	            {{message}}
	        </div>
	        {{/if}}
	    </div>
	</template>

	<template id="tmpl-popup-error">
	    <div class="popup-mesage popup-mesage--error" id="popup-error" aria-hidden="true" tabindex="-1">
	        <button class="popup-mesage__close j-close-modal" data-target="#popup-error" aria-label="Закрыть"></button>

	        {{#if title}}
	        <header class="popup-mesage__header popup-mesage__header--failure">
	            {{title}}
	        </header>
	        {{/if}}

	        {{#if message}}
	        <div class="popup-mesage__body">
	            {{message}}
	        </div>
	        {{/if}}
	    </div>
	</template>

	<template id="tmpl-send-message">
		<div class="modal" aria-hidden="true" tabindex="-1" id="send-message">
			<form action="/api/send-message" method="POST" class="modal__dialog modal__dialog--preload is-active j-ajax-form">
				<div class="modal__dialog__content">
					<button type="button" class="modal__close j-close-modal" data-target="#send-message"></button>

					<input type="hidden" name="session" value="{{ session }}">

					<div class="modal__header">
						<div class="modal__title">Отправить видео</div>
					</div>

					<div class="modal__body">
						<label class="label">
							<span class="label__name">Имя</span>
							<input name="name" class="input">
						</label>

						<label class="label">
							<span class="label__name">Номер телефона</span>
							<input name="phone" id="send-phone" class="input">
						</label>

						<label class="label">
							<span class="label__name">Электронная почта</span>
							<input name="email" id="send-email" class="input">
						</label>

						<label class="ui-checkbox">
	                        <input type="checkbox" name="photo" value="1" class="ui-checkbox__input" checked>
	                        <span class="ui-checkbox__visible" role="checkbox" aria-checked="false" tabindex="0"> </span>
	                        <span class="ui-checkbox__label">
	                            <span class="ui-checkbox__label__middle">Добавить фотографию в письмо</span>
	                        </span>
	                    </label>
					</div>

					<div class="modal__footer">
						<button type="button" class="button-reset j-close-modal" data-target="#send-message">
							<span class="button-reset__underline">Отменить</span>
						</button>

						<button type="submit" class="button-submit" style="background-color: <?= $this->params['style_button_bg']; ?>; color: <?= $this->params['style_button_text']; ?>;">Отправить</button>
					</div>
				</div>
			</form>
		</div>
	</template>

    <div class="layout-wrapper__container">

        <aside class="sidebar" style="background-color: <?= $this->params['style_sidebar_bg']; ?>; color: <?= $this->params['style_sidebar_text']; ?>;">
        	<div class="sidebar__scroll" id="sidebar"></div>
        </aside>

        <div class="container">

        	<header class="header">

        		<div class="header__event">
        			<?= $this->params['event_name']; ?>
        		</div>

		        <div class="logo">
		        	<?php if (!empty($this->params['logo'])): ?>
		        	<img src="<?= $this->params['logo']; ?>" alt="">
		        	<?php endif; ?>
		        </div>

			</header>

			<main class="content" id="content">

	        	<?php if ($mode == 'gif'): ?>
	        		<div id="player-gif" class="video-gif"></div>
	        	<?php else: ?>
	        		<!-- controls -->
	        		<video id="player-video" class="video-js vjs-default-skin" preload="auto" loop data-setup='{"width":auto,"height":auto,"fluid":true,"aspectRatio":"4:3"}'></video>
	        	<?php endif; ?>

	 			<!-- j-open-modal -->
				<button class="button" data-modal="tmpl-send-message" id="send-video" style="background-color: <?= $this->params['style_button_bg']; ?>; color: <?= $this->params['style_button_text']; ?>;">
					<?= $this->params['send_button']; ?>
				</button>

	        </main>

        </div>

    </div>

</div>

<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/video.min.js"></script>
<script src="/static/js/template.js"></script>
<script src="/static/js/template7.min.js"></script>
<script src="/static/js/maskedinput.min.js"></script>
<script src="/static/js/modal.min.js"></script>
<script src="/static/js/email-autocomplete.min.js"></script>
<script src="/static/js/app.js"></script>

</body>
</html>